package sample;
import java.sql.SQLException;
import java.util.Date;

/**
 * Abstract Class for Application Data.
 */
public class ApplicationData extends SubmissionForm{
    private DatabaseUtil databaseUtil = new DatabaseUtil();

    private String ttbid;
    private int repid;
    private String serial;
    private String address;
    private String fancyName;
    private String formula;

    private int permit_no;
    private String infoOnBottle;
    private String source_of_product;
    private String type_of_product;
    private String brand_name;
    private String phone_number;
    private String email;
    private String date;
    public String applicantName;
    private String alcoholType;
    private String alcoholContent;
    private int type1;
    private String type2;
    private int type3;

    /**
     * Creates an instance of Application Data.
     * @param formID ID number of the form.
     * @param acceptanceInfo Information regarding the acceptance of the application; see the AcceptanceInformation class for more details.
     * @param ttbid ID generated by the TTB for tracking.
     * @param repid Representative ID.
     * @param serial Serial number for the application.
     * @param address Manufacturer's address.
     * @param fancyName Fanciful name of the alcohol.
     * @param formula Formula for the alcohol.
     * @param permit_no Number of the permit.
     * @param infoOnBottle String representing any additional info on the bottle.
     * @param source_of_product Location from which the product originated.
     * @param type_of_product Alcohol type.
     * @param brand_name Brand name of the alcohol.
     * @param phone_number Phone number for the manufacturer.
     * @param email Manufacturer's email address.
     * @param date Date of application.
     * @param applicantName Name of the applicant.
     * @param alcoholType Type of alcohol.
     * @param alcoholContent Alcohol content metric.
     */
    public ApplicationData(int formID, AcceptanceInformation acceptanceInfo, String ttbid, int repid, String serial, String address, String fancyName,
                           String formula, int permit_no,
                           String infoOnBottle, String source_of_product, String type_of_product,
                           String brand_name, String phone_number, String email, String date,
                           String applicantName, String alcoholType, String alcoholContent, int type1, String type2, int type3) {
        super(formID, acceptanceInfo);
        this.ttbid = ttbid;
        this.repid = repid;
        this.serial = serial;
        this.address = address;
        this.fancyName = fancyName;
        this.formula = formula;
        this.permit_no = permit_no;
        this.infoOnBottle = infoOnBottle;
        this.source_of_product = source_of_product;
        this.type_of_product = type_of_product;
        this.brand_name = brand_name;
        this.phone_number = phone_number;
        this.email = email;
        this.date = date;
        this.applicantName = applicantName;
        this.alcoholType = alcoholType;
        this.alcoholContent = alcoholContent;
        this.type1 = type1;
        this.type2 = type2;
        this.type3 = type3;
    }

    //#######################################GETTERS IN PROGRESS################################
    public String getSulfite(){return "";}

    public String getGrapevar(){return "";}

    public String getVintage(){return "";}

    public String getAppellation(){return "";}

    public String getBottler(){return "";}

    public String getHealthWarning(){return "";}
    //##########################################################################################

    public String getSource_of_product() {
        return source_of_product;
    }

    public String getType_of_product() {
        return type_of_product;
    }

    public String getAlcoholType() {
        return alcoholType;
    }


    public int getPermit_no() {
        return permit_no;
    }

    public int getType1() {
        return type1;
    }

    public String getType2() {
        return type2;
    }

    public int getType3() {
        return type3;
    }

    public String getBrand_name() {
        return brand_name;
    }

    public void setBrand_name(String brand_name) {
        this.brand_name = brand_name;
    }

    public String getPhone_number() {
        return phone_number;
    }

    public void setPhone_number(String phone_number) {
        this.phone_number = phone_number;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public String getApplicantName() {
        return applicantName;
    }

    public void setApplicantName(String applicantName) {
        this.applicantName = applicantName;
    }

    public String getAlcoholContent() {
        return alcoholContent;
    }

    public void setAlcoholContent(String alcoholContent) {
        this.alcoholContent = alcoholContent;
    }

    public String getTtbid() {
        return ttbid;
    }

    public int getRepid() {
        return repid;
    }

    public String getSerial() {
        return serial;
    }

    public String getAddress() {
        return address;
    }

    public String getFancyName() {
        return fancyName;
    }

    public String getFormula() {
        return formula;
    }

    public String getInfoOnBottle() {
        return infoOnBottle;
    }

    public String getStatus() throws SQLException{
        return databaseUtil.getStatus(this.getFormID());
    }

    public int getAssociatedAlchID() throws SQLException{
        return databaseUtil.getAidOfForm(this.getFormID());
    }
}
